<a href="https://colab.research.google.com/github/khetpatiparn/Learn_Python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#การสร้าง Array 0, 1, 2 และ 3 มิติ
คำสั่งหรือฟังก์ชั่นในการสร้าง array คือ <br> <code>array(parameter)</code>
<br>
วิธีการสังเกตมิติจากโค้ดให้ ดูที่วงเล็บ หรือใช้ argument <code>ndim</code>


##การสร้าง Array 0 และ 1 มิติ


In [ ]:
import numpy as np

In [ ]:
arr = np.array(1)
arr

array(1)

In [ ]:
arr = np.array(2)
arr

array(2)

In [ ]:
arr.ndim #show dimension of array

0

In [ ]:
a = np.array([1,2,3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
li = [1,2,3,4,5]
b = np.array(li)

In [ ]:
b

array([1, 2, 3, 4, 5])

In [ ]:
tu = (10,20,30,40,50,60,70,80,90,100) #ใช้เป็น tuple ก็ได้
c = np.array(tu)

In [ ]:
c

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
c.ndim

1

##การสร้าง Array 2 มิติ
ต้องระบุในแบบ แถว และ คอลัมน์

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
li = [[1,2,3,4,5],[10,20,30,40,50],[-1,-2,-3,-4,-5]]

In [ ]:
b = np.array(li)
b

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50],
       [-1, -2, -3, -4, -5]])

In [ ]:
b.ndim

2

In [ ]:
tu = ((2,4,6,8,10),(1,3,5,7,9))
c = np.array(tu)
c

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [ ]:
c.ndim

2

##การสร้าง Array 3 มิติ
มีความลึกเข้ามาเพิ่ม

In [ ]:
import numpy as np

In [ ]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
a.ndim

3

#การเข้าถึงข้อมูลใน Array 1, 2 และ 3 มิติ
ใช้รูปแบบการเข้าถึงสมาชิกด้วย index

##การเข้าถึงสมาธิใน Array 1 มิติ

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a[3]

4

In [ ]:
a[-1] #เข้าถึงตัวสุดท้าย

5

In [ ]:
a[0] = 100
a

array([100,   2,   3,   4,   5])

##การเข้าถึงสมาธิใน Array 2 มิติ
เรียก แถว ก่อน คอลัมน์ <br>
<code>a[row][column]</code>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a[1][1] 

4

In [ ]:
a[0][1] = 500
a

array([[  1, 500],
       [  3,   4],
       [  5,   6]])

In [ ]:
a[-1][-2]

5

##การเข้าถึงสมาธิใน Array 3 มิติ
<code>a[dept][row][column]</code>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[[1,2,3],[4,5,6]]])
a

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
a.ndim

3

In [ ]:
a[0][1][1]

5

In [ ]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
b.ndim

3

In [ ]:
b[0][0][2]

3

In [ ]:
b[1][0][1]

8

#ชนิดข้อมูลที่ใช้ใน Numpy
1. Interger
2. Float
3. String
4. Boolean
5. Complex
6. Object

สามารถเช็คชนิดข้อมูลของอาเรย์หรือเปลี่ยนชนิดข้อมูลได้ด้วย attribute <code>dtype</code>

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
#เปลี่ยนชนิดข้อมูล array จาก integer => float
a = np.array([1,2,3,4,5], dtype="float")
a

array([1., 2., 3., 4., 5.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a = np.array([1,2,3,4,5], dtype="complex")
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [ ]:
a.dtype

dtype('complex128')

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype="float")
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
b.dtype

dtype('float64')

#Matrix


##Zero Matrix
ใช้ function <code>zeros(shape)</code>
<br>
shape คือ รูปร่างของ matrix เขียนเป็น list หรือ tuple ก็ได้

In [ ]:
import numpy as np

In [ ]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
b = np.zeros([3,3])
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b = np.zeros([3,3], dtype ="int")
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
c = np.zeros((5,5,5), dtype="complex")
c

array([[[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+

In [ ]:
c.ndim

3

##One Matrix
ใช้ function <code>ones(shape)</code>

In [ ]:
import numpy as np

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((4,3),dtype="int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones((2,4,4),dtype="int")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

##Matrix ค่าคงที่
เช่น อยากให้เป็นเลข 7 ทั้งหมด หรือ 10 ทั้งหมด หรือ ... ทำอย่างไร
<br>
ใช้ function <code>full(shape, full_value)</code>

In [ ]:
import numpy as np

In [ ]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [ ]:
np.full([4,4], 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.full((2,2,3), 9)

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])


##Empty
เป็นการสร้าง Array เปล่าๆ ขึ้นมาโดยสนใจแค่ขนาดไม่ได้สนใจค่าข้างใน โดยค่าข้างในจะเป็นการสุ่มขึ้นมา
<br>
ใช้ function <code>empty(shape)</code>

In [ ]:
np.empty(5)

array([3.31274573e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000])

In [ ]:
np.empty([3,3])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
np.empty([2,4,4])

array([[[3.45238212e-316, 1.05235983e-321, 0.00000000e+000,
         0.00000000e+000],
        [6.92640646e-310, 5.02034658e+175, 1.00650066e-046,
         9.58869399e-043],
        [1.56047022e+184, 3.75934834e+179, 6.38446434e-067,
         1.14428494e+243],
        [2.59903818e-144, 3.80985069e+180, 1.35617292e+248,
         7.82691079e-077]],

       [[7.12560134e-091, 1.71696220e+185, 3.63526406e+174,
         9.27764063e-072],
        [4.99874558e+217, 5.49419094e-143, 2.91237123e+257,
         5.56111702e+180],
        [5.74015544e+180, 1.94919988e-153, 2.59027856e-144,
         2.59903818e-144],
        [5.27485035e-091, 6.76090315e-067, 9.05797261e-043,
         6.92558614e-310]]])

##Identity Matrix
Matrix เอกลักษณ์ ขนาด 2 มิติ
<br>
ใช้ function <code>identity(n)</code>
<br>
n คือ จำนวนแถวของ Matrix

ถ้าต้องการ Identity Matrix ที่สามารถระบุขนาดได้
<br>
ใช้ function <code>eye(N, M, k)</code>
<br>
N คือ แถว<br>
M คือ คอลัมน์<br>
k คือ ตำแหน่งเลข 1 จะให้ขึ้นหรือลง

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(10, dtype="int")

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [ ]:
np.eye(6,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.]])

In [ ]:
#เปลี่ยนตำแหน่งเลข 1 ด้วย k
np.eye(6,8, k = 1)

array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.]])

In [ ]:
np.eye(6,8, k = -2, dtype = "int")

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0]])

#Linspace
เป็นการสร้าง Array 1 มิติ ขึ้นมาแบบกำหนดช่วงที่ต้องการได้ โดยค่าที่อยู่ในช่วงจะมีความห่างที่เท่ากัน สามารถใช้ plot graph ได้ <br>
ใช้ function <code>linspace(start, stop, num, endpoint=True/False)</code><br>
start : ตัวเริ่มต้น<br>
stop : สุดสุดท้าย<br>
n : จำนวนสมาชิกใน Array 1 มิติ (default ที่ 50 ตัว)<br>
endpoint : เอาตัวสุดท้ายด้วยมั้ย


In [ ]:
import numpy as np

In [ ]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.linspace(2,5,endpoint=False)

array([2.  , 2.06, 2.12, 2.18, 2.24, 2.3 , 2.36, 2.42, 2.48, 2.54, 2.6 ,
       2.66, 2.72, 2.78, 2.84, 2.9 , 2.96, 3.02, 3.08, 3.14, 3.2 , 3.26,
       3.32, 3.38, 3.44, 3.5 , 3.56, 3.62, 3.68, 3.74, 3.8 , 3.86, 3.92,
       3.98, 4.04, 4.1 , 4.16, 4.22, 4.28, 4.34, 4.4 , 4.46, 4.52, 4.58,
       4.64, 4.7 , 4.76, 4.82, 4.88, 4.94])

In [ ]:
np.linspace(1,11,5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [ ]:
np.linspace(1,11,5, endpoint =False)

array([1., 3., 5., 7., 9.])

#Arange
เป็นการสร้าง Array 1 มิติขึ้นแบบกำหนดช่วงข้อมูลที่ต้องการได้<br>
ใช้ function <code>arange(start, stop, step)</code>

In [ ]:
import numpy as np

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(-5,6, dtype="float")

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [ ]:
np.arange(4,11,dtype = "complex")

array([ 4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,11,5)

array([1, 6])

#Random
เป็นการสร้าง Array ขึ้นมาแบบกำหนดช่วงโดยตัวเลขที่ออกมาจะเป็นตัวเลขแบบสุ่มในช่วง [0.0, 1.0)<br>
ใช้ function <code>random.random(size)</code>

In [ ]:
import numpy as np

In [ ]:
np.random.random((10,10))

array([[0.78018941, 0.70970035, 0.12994544, 0.89712697, 0.52459285,
        0.61056192, 0.3204099 , 0.61898775, 0.15440013, 0.55616289],
       [0.44341151, 0.3320437 , 0.60702649, 0.44650149, 0.40132312,
        0.22293378, 0.84440477, 0.17977987, 0.64852483, 0.80566956],
       [0.54725984, 0.6720726 , 0.99774867, 0.06713415, 0.89088477,
        0.72865984, 0.48633176, 0.36886723, 0.78312961, 0.86811699],
       [0.68899246, 0.5146612 , 0.80021933, 0.19532602, 0.02273247,
        0.08529069, 0.70153687, 0.38853486, 0.62131059, 0.15040613],
       [0.23698766, 0.61304026, 0.63445628, 0.00274368, 0.68001869,
        0.55775329, 0.63219585, 0.59864549, 0.94279018, 0.24084682],
       [0.87678437, 0.2225841 , 0.03610462, 0.13467058, 0.4148107 ,
        0.26060772, 0.54744715, 0.45308063, 0.84186562, 0.64007541],
       [0.75256459, 0.2268368 , 0.98635929, 0.60529156, 0.95227684,
        0.93441178, 0.15904834, 0.80203708, 0.13384181, 0.85852534],
       [0.55422473, 0.12117257, 0.9828969

In [ ]:
np.random.random((2,2))

array([[0.48073558, 0.14030018],
       [0.68427566, 0.25685784]])

#Numpy Attribute
1. ndim : บอกมิติ<br>
2. dtype : บอกชนิดข้อมูล<br>
3. shape : บอกรูปร่าง<br>
4. size : บอกจำนวนสมาชิกใน Array <br>
5. itemsize : บอกขนาด byte ของชนิดข้อมูล


In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype= "complex")
b.dtype

dtype('complex128')

In [ ]:
a.shape

(5,)

In [ ]:
b.shape

(3, 3)

In [ ]:
a.size

5

In [ ]:
b.size

9

In [ ]:
a.itemsize

8

In [ ]:
b.itemsize

16

#Slice Array 1 และ 2 มิติ

##Slice Array 1 มิติ
<code>x[start:stop:step]</code>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[2]

3

In [ ]:
a[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[7:]

array([ 8,  9, 10])

In [ ]:
a[:5]

array([1, 2, 3, 4, 5])

In [ ]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [ ]:
b = np.array([20,10,30,50,40])
b

array([20, 10, 30, 50, 40])

In [ ]:
b[1:]

array([10, 30, 50, 40])

In [ ]:
b[3:]

array([50, 40])

In [ ]:
b[:3]

array([20, 10, 30])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[3:7]

array([4, 5, 6, 7])

In [ ]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:9:2]

array([3, 5, 7, 9])

In [ ]:
b

array([20, 10, 30, 50, 40])

In [ ]:
b[1:4]

array([10, 30, 50])

In [ ]:
b[1:4:2]

array([10, 50])

In [ ]:
c = np.array([10,30,40,50,60,70,75,90])
c

array([10, 30, 40, 50, 60, 70, 75, 90])

In [ ]:
c[:]

array([10, 30, 40, 50, 60, 70, 75, 90])

In [ ]:
c[::2]

array([10, 40, 60, 75])

In [ ]:
c[::3]

array([10, 50, 75])

##Slice Array 2 มิติ
<code>x[row,col] => x[start:stop:step, start:stop:step]</code>

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
x[2:,2:]

array([[9]])

In [ ]:
x[2:,1:]

array([[8, 9]])

In [ ]:
x[:,2:]

array([[3],
       [6],
       [9]])

In [ ]:
x[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
x[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x[:2,2:]

array([[3],
       [6]])

In [ ]:
x[1:2,1:2]

array([[5]])

In [ ]:
x[::2,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
x[1:2,:]

array([[4, 5, 6]])

In [ ]:
x[:,::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
x[:,1:2]

array([[2],
       [5],
       [8]])

#Index Operator

In [ ]:
import numpy as np

In [ ]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
index = np.array([1,5,7])
index

array([1, 5, 7])

In [ ]:
x[index]

array([2, 6, 8])

In [ ]:
x[[1,5,7]]

array([2, 6, 8])

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
b[[0,2],[2,0]]

array([3, 7])

In [ ]:
b[[0,2],[1]]

array([2, 8])

In [ ]:
b[[0,2],[2]]

array([3, 9])

In [ ]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[[0,3,0,3,0,3,0]]

array([1, 4, 1, 4, 1, 4, 1])

In [ ]:
m = np.array([[1,-2,3],[4,-5,-6]])
m

array([[ 1, -2,  3],
       [ 4, -5, -6]])

In [ ]:
m[m<0]

array([-2, -5, -6])

In [ ]:
m[m>2]**2

array([ 9, 16])

#Arithmetic Operator
การ + - * / Array สามารถทำได้ก็ต่อเมื่อมีขนาดและมิติเท่ากัน

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a+10

array([11, 12, 13, 14])

In [ ]:
a-5

array([-4, -3, -2, -1])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
a%2

array([1, 0, 1, 0])

In [ ]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [ ]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [ ]:
a + b

array([2, 4, 6, 8])

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y = np.array([[7,8,9],[10,11,12]])
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
x + y

array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
x * y

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
x - y

array([[-6, -6, -6],
       [-6, -6, -6]])

In [ ]:
x / y

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

#Broadcasting
วิธีทำให้ Array ที่มิติและขนาดต่างกันสามารถ + - * / ร่วมกันได้<br>
<code>x = np.array([[1,2],[3,4],[5,6]])<br>y = np.array([1,2])
<br>x + y</code><br>
โดย array ที่มีมิติต่างกันแต่ขนาดเท่ากันจะถูก broadcast ไปเป็นมิติที่เท่ากันและเกิดการทำซ้ำ

In [ ]:
x = np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
y = np.array([1,2])
y

array([1, 2])

In [ ]:
x+y

array([[2, 4],
       [4, 6],
       [6, 8]])

In [ ]:
x+[10]

array([[11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
z = np.array([[10],[20],[30]])
z

array([[10],
       [20],
       [30]])

In [ ]:
x+z

array([[11, 12],
       [23, 24],
       [35, 36]])

#Reshape & Resize
เป็นการจัดเรียงมิติและขนาดตามที่ต้องการแต่ว่า reshape จะไม่มีการเปลี่ยนแปลงรูปแบบข้อมูลถาวร ส่วน resize จะมีการเปลี่ยนแปลงข้อมูลถาวร
<br>
<code>reshape(shape)<br>
resize(shape)</code>

In [ ]:
import numpy as np

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.reshape([2,5])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a#a ไม่มีการเปลียนแปลงข้อมูลถาวร จึงต้องมีการสร้างตัวแปรเข้ามารับค่า

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b.resize([2,5])

In [ ]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#Flatten
เป็นการเปลี่ยนแปลง Array หลายมิติให้เป็น 1 มิติ
แต่ flatten จะไม่มีการเปลี่ยนแปลงค่าแบบถาวรเหมือน reshape ส่วนจะไม่มีการเปลี่ยนแปลงขนาดถาวรเหมือนกันแต่จะสามารถลิงก์ข้อมูลในค่าเดิมเปลี่ยนแปลงได้ด้วย ravel
<br>
<code>flatten()<br>
ravel()</code>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b = a.flatten()
b

array([1, 2, 3, 4, 5, 6])

In [ ]:
b[0] = 5
b

array([5, 2, 3, 4, 5, 6])

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
c = a.ravel()
c

array([1, 2, 3, 4, 5, 6])

In [ ]:
c[0] = 20

In [ ]:
a

array([[20,  2],
       [ 3,  4],
       [ 5,  6]])

In [ ]:
z = np.array([[1,2],[3,4],[5,6]])
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
z.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
z

array([[1, 2],
       [3, 4],
       [5, 6]])

#Transpose

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = a.transpose()
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
b.shape

(3, 2)

#ฟังก์ชันทางสถิติ
ตัวอย่างฟังก์ชันที่ใช้กับ Array 1 มิติ
<br><code>
sum() : หาผลรวมของสมาชิก<br>
pord() :หาผลคูณของสมาชิก<br>
max() : หาค่าสูงสุดสุดของสมาชิก<br>
min() :หาค่าต่ำสุดของสมาชิก<br>
argmax() : แสดง Index  ของค่าสูงสุด<br>
argmin() : แสดง Index ของค่าต่ำสุด
</code><br>
กรณี 2 มิติ จะต้องเรียกใช้ฟังก์ชันลักษณะออบเจกแทนและ แถว ใช้ axis = 1 คอมลัมน์ ใช้ axis = 0

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,20,5,38,12,100])
a

array([  1,  20,   5,  38,  12, 100])

In [ ]:
a.sum()

176

In [ ]:
a.prod()

4560000

In [ ]:
a.max()

100

In [ ]:
a.min()

1

In [ ]:
a.argmin()

0

In [ ]:
a.argmax()

5

In [ ]:
#กรณี 2 มิติ
b = np.array([[-1,-10,5],[10,20,30],[15,20,18]])
b

array([[ -1, -10,   5],
       [ 10,  20,  30],
       [ 15,  20,  18]])

In [ ]:
np.min(b,axis = 1)#row

array([-10,  10,  15])

In [ ]:
np.min(b,axis = 0)#column

array([ -1, -10,   5])

In [ ]:
np.max(b,axis = 1)#row

array([ 5, 30, 20])

In [ ]:
np.max(b,axis = 1)#column

array([ 5, 30, 20])

#Dot Product
การคูณแบบ Matrix
<br>ใช้ function <code>dot()</code> 

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
b = np.array([[1],[2],[1]])
b

array([[1],
       [2],
       [1]])

In [ ]:
b.shape

(3, 1)

In [ ]:
c = a.dot(b)
c

array([[ 8],
       [20]])

In [ ]:
c.shape

(2, 1)

#Concatenate & Append
<code>concatenate()</code> เป็นการนำ Array มารวมกันส่วน <code>append(arr,value,axis)</code> เป็นการเพิ่มข้อมูลมาต่อท้าย


In [ ]:
import numpy as np

In [ ]:
a = np.array([3,4,2,6])
a

array([3, 4, 2, 6])

In [ ]:
b = np.array([8,6,5,10])
b

array([ 8,  6,  5, 10])

In [ ]:
np.concatenate([a,b])

array([ 3,  4,  2,  6,  8,  6,  5, 10])

In [ ]:
np.append(a,500)

array([  3,   4,   2,   6, 500])

In [ ]:
np.append(a,[10,20,30])

array([ 3,  4,  2,  6, 10, 20, 30])

In [ ]:
np.append(a,[[10,20,30]])

array([ 3,  4,  2,  6, 10, 20, 30])

In [ ]:
a

array([3, 4, 2, 6])

In [ ]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.append(c,[[7,8,9]],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Insert
<code>insert(arr,index,value)</code> เพิ่มข้อมูลเหมือนกันแต่สามารถแทรกข้อมูลตาม index ที่ต้องการได้

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,4,5,8])
a

array([1, 2, 4, 5, 8])

In [ ]:
np.insert(a,1,100)

array([  1, 100,   2,   4,   5,   8])

In [ ]:
np.insert(a,(1,3,5),200) #เพิ่มหลายๆ index พร้อมกันได้

array([  1, 200,   2,   4, 200,   5,   8, 200])

##insert แบบ Array 2 มิติ

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
np.insert(a,1,100,axis  = 0)

array([[  1,   2],
       [100, 100],
       [  3,   4]])

In [ ]:
np.insert(a,1,100,axis  = 1)

array([[  1, 100,   2],
       [  3, 100,   4]])

In [ ]:
np.insert(a,1,[10,50],axis  = 0)

array([[ 1,  2],
       [10, 50],
       [ 3,  4]])

In [ ]:
np.insert(a,1,[10,50],axis  = 1)

array([[ 1, 10,  2],
       [ 3, 50,  4]])

In [ ]:
np.insert(a,1,[[10],[50]],axis  = 1)

array([[ 1, 10, 50,  2],
       [ 3, 10, 50,  4]])

In [ ]:
np.insert(a,1,[[10],[50]],axis  = 0)

array([[ 1,  2],
       [10, 10],
       [50, 50],
       [ 3,  4]])

#Delete
ใช้ function <code>delete(arr,index,axis)</code>

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.delete(a,2)

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b = a.reshape((4,3))
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.delete(b,0,axis=0)

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.delete(b,0,axis=1)

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

#Split
เป็นการแบ่ง Array ออกเป็นส่วนๆและต้องแบ่งให้สอดคล้องกับสมาชิกด้วย<br>
ใช้ function <code>split(arr,n)</code><br>
n : จำนวนที่ต้องการแบ่ง

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
np.split(a,5)

[array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14, 15, 16]),
 array([17, 18, 19, 20])]

In [ ]:
np.split(a,4)

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20])]

##Split Array 2 มิติ
<code>hsplit() คือ แบ่งส่วนแบบ คอลัมน์<br>
vsplit() คือ แบ่งส่วนแบบ แถว</code>


In [ ]:
a = np.arange(1,21).reshape((5,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
np.hsplit(a,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]), array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]), array([[ 3],
        [ 7],
        [11],
        [15],
        [19]]), array([[ 4],
        [ 8],
        [12],
        [16],
        [20]])]

In [ ]:
np.vsplit(a,5)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([[17, 18, 19, 20]])]

In [ ]:
np.hsplit(a,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20]])]